language: node_js
node_js:
  - 8
cache:
  directories:
    - "~/.npm"
before_script:
  - npm i -g gatsby
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
  - npm run coveralls
env:
  global:
    - secure: EPSk1D2kYmfqqQZdrt1g8UJCOfONMQOeM3rquiGJurplniwxsaU85EYGjp98UEtpIR3+ZLj0GOPvuInbcJfAtoYN/wbX8bWUANrgTXeCR/i8KQSIlDtRViTqS4xTDFHPlT4EdGfKuWxRX1pPLwEI0s8QPnMb6mFd/ANdOcdNDDIebjz2tGiUdatUvmhgI6ZUnLUM4R7kgGluwgjV0x/qdNnF3SCij7D+AyexK2WdNHteaC3EdL7KIx9q2vEPcUWJ8ZbgF2ivnQUkj4trpACWowSre3J0T4nCIc4bkdmOEN6CMez+foYdLiTNs6lUe2F4r6n9NE9dwF5v75YWsjgk5mLwJEJm0wToPzD7PNIbzFGlR3vL8xrZZ+yI9gaGJra/ThdYWb9K33EPI/Qsa7F0iojDUQgMhfM4ZHktqPZjR8rMB+A3azZLKmUadNyjS0u/+3UmzM4I/1I04VXR6OiiLAcEbQXTVBUR1mCs1ONsICPf6ho2Ld0OCSlHOta9JNPe/sEhUx9yAL4CFkzCqUOfLUT5mwNhab9rG0Dlrj5hntn+c5JdQi5Tp2cxwbCgHddBi+nGY8vU2POiqqNiI2ogmOmEmVj1audTsuQ8XNkFeNxrjgsp5dKCpjvr1fvgWPhudWYqgWgLSze5RKD7+q73BvU2UTNlHORsAYO5RHh1AzE=
    - secure: oeiUYKQ1nviGta9iljN+NM2rzrLCZLTXi52HyEEPPNl8epR8NEf+k5huLteqT27fGzN7h9tIlMmvKlfSEqbwol0ceqkUQZ7TU6BIc+0ujVVkBsOn+t0wS+wH/c12QfaVsMzals+H1CR9l85fsulc6xeVEUf5YGQOFC6oBgVMU7R8NQnKFMGuYfnio+6oleGdyCy903C2TpU4QeLwwAPa94bHR/mCDTDmzePyHl2MUJ302D96mr6eazDGAy8CH/bCTXt6TrrIMKfH/Z1KQnvRDiIHux1SC+5WDRvNJ23Y4Pw09RQz1MhVpVPxBH2a46abM9ic16OVdhV+dmKIzfae6qR5OACnaUuYLIqFb1z4Bp1xB0S/w0RO/OiLd+sT0jXj7L+alVcfU7zYF49X3ngRsOS8j5SwBh1rm9OyPWla1VPmZR1hBG9pOGxjclFreRVf01xRoi7ZG6JiqzRXVxV0/56qcKmrKtdwDg+s2FfWHqCQTruxxWX1CczI/w9YThfHbzcOyxyVliu67OhO6DwluxJeQv8XAOZI2cXJl4Z4XXEoO22JYPrWJd3f4M6Ncx9OOOIP3tvHX8vlOG+8xBzjOaltRWO+inkAAqopBMl6j3eG310QcQ2OEXLslSC6hRGRHlKS5v85DDusTn/isakmEej7ow+pAs8HnuMBwYxdwZM=
