language: node_js
node_js: 12
before_script:
  - npm i -g gatsby
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
  - npm run coveralls
env:
  global:
    # NPM_TOKEN
    - secure: iGR37Vwp3+XDMvEr6QIU6GhuL3/+VJAeyFgrrjwEZI6zFu0sup9bgXmiamgCblPMOh5LPvF9l75PnnwlxUQ5wMrG3ZC5zcYq/dU41N8dTlg5YJ3C9VuaN07xFy5Z15OWq4Xz9m5WfBVz1EHreWafdPb+ek4z8aPBqBshLwV0xj09PesYkI3XvXL6AP5j4aV68vHiZq8S8V488Rhky7QkIUEs/MBfBef+zsr/Oe9Q+dsgxyoX8ZRgSvpT0JL8Z6rRB0VhS7NtrtPLSpi4LIybMV3OCMW0oy0GrEjmWUFS+3cVGsHzpTly6vwEyXYH+yEjNqGCbLkN+LB+xwO5iqy3AtKIz/Z2VT/JPFy7Tm2Y3UrkfWpq87fjZgSThZ+16GPTr1r+uX1f0nnnnnAM6F4U16chvFuq76lZDhUaK84LRTAbWyRu6PJbAedaZsMzr0TioIWs8484GQZbhBH1xX0aLTSMQQ7Djk/4w0cq2msk9PYJ7Ae6sUiHr2apm3fKPLwksbKPINFQ05ofKkg8gO6AbzhPAyKAWqv4y8OD/Y6XsW/9DVXmwH1aWNTaIu1TzAVW52oqrUqF4eRQUFo0c4ALBdMLpD9xyuIyS3Ia/so5CvhZV6VgArcCn7b/U8GdFmA5bFQzepGIjwTkqG6XmtL6PdcBFc5v6SKUXnme59jMqF0=
    - secure: oeiUYKQ1nviGta9iljN+NM2rzrLCZLTXi52HyEEPPNl8epR8NEf+k5huLteqT27fGzN7h9tIlMmvKlfSEqbwol0ceqkUQZ7TU6BIc+0ujVVkBsOn+t0wS+wH/c12QfaVsMzals+H1CR9l85fsulc6xeVEUf5YGQOFC6oBgVMU7R8NQnKFMGuYfnio+6oleGdyCy903C2TpU4QeLwwAPa94bHR/mCDTDmzePyHl2MUJ302D96mr6eazDGAy8CH/bCTXt6TrrIMKfH/Z1KQnvRDiIHux1SC+5WDRvNJ23Y4Pw09RQz1MhVpVPxBH2a46abM9ic16OVdhV+dmKIzfae6qR5OACnaUuYLIqFb1z4Bp1xB0S/w0RO/OiLd+sT0jXj7L+alVcfU7zYF49X3ngRsOS8j5SwBh1rm9OyPWla1VPmZR1hBG9pOGxjclFreRVf01xRoi7ZG6JiqzRXVxV0/56qcKmrKtdwDg+s2FfWHqCQTruxxWX1CczI/w9YThfHbzcOyxyVliu67OhO6DwluxJeQv8XAOZI2cXJl4Z4XXEoO22JYPrWJd3f4M6Ncx9OOOIP3tvHX8vlOG+8xBzjOaltRWO+inkAAqopBMl6j3eG310QcQ2OEXLslSC6hRGRHlKS5v85DDusTn/isakmEej7ow+pAs8HnuMBwYxdwZM=
